a = int(input())
b = int(input())
a2 = (a * a)
b2 = (b * b)
kvadrat = ((a + b) * (a + b))
summa_kvadratov = ((a * a) + (b * b))
print('Квадрат суммы', a, 'и', b, 'равен', kvadrat)
print('Сумма квадратов', a, 'и', b, 'равна', summa_kvadratov)

# альтернативный и правильный вариант a, b = int(input()), int(input())